/* Auto-generated by genmsg_cpp for file /home/lapyr/catkin_ws_slam/src/EVS_SLAM/Examples/ROS/evs_slam/msg/array2D.msg */
#ifndef EVS_SLAM_MESSAGE_ARRAY2D_H
#define EVS_SLAM_MESSAGE_ARRAY2D_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace evs_slam
{
template <class ContainerAllocator>
struct array2D_ {
  typedef array2D_<ContainerAllocator> Type;

  array2D_()
  : data()
  {
  }

  array2D_(const ContainerAllocator& _alloc)
  : data(_alloc)
  {
  }

  typedef std::vector<int8_t, typename ContainerAllocator::template rebind<int8_t>::other >  _data_type;
  std::vector<int8_t, typename ContainerAllocator::template rebind<int8_t>::other >  data;


  typedef boost::shared_ptr< ::evs_slam::array2D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::evs_slam::array2D_<ContainerAllocator>  const> ConstPtr;
}; // struct array2D
typedef  ::evs_slam::array2D_<std::allocator<void> > array2D;

typedef boost::shared_ptr< ::evs_slam::array2D> array2DPtr;
typedef boost::shared_ptr< ::evs_slam::array2D const> array2DConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::evs_slam::array2D_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::evs_slam::array2D_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace evs_slam

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::evs_slam::array2D_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::evs_slam::array2D_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::evs_slam::array2D_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ac9c931aaf6ce145ea0383362e83c70b";
  }

  static const char* value(const  ::evs_slam::array2D_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xac9c931aaf6ce145ULL;
  static const uint64_t static_value2 = 0xea0383362e83c70bULL;
};

template<class ContainerAllocator>
struct DataType< ::evs_slam::array2D_<ContainerAllocator> > {
  static const char* value() 
  {
    return "evs_slam/array2D";
  }

  static const char* value(const  ::evs_slam::array2D_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::evs_slam::array2D_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int8[] data\n\
\n\
";
  }

  static const char* value(const  ::evs_slam::array2D_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::evs_slam::array2D_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.data);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct array2D_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::evs_slam::array2D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::evs_slam::array2D_<ContainerAllocator> & v) 
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // EVS_SLAM_MESSAGE_ARRAY2D_H

