/* Auto-generated by genmsg_cpp for file /home/lapyr/catkin_ws_slam/src/EVS_SLAM/Examples/ROS/evs_slam/msg/Num.msg */
#ifndef EVS_SLAM_MESSAGE_NUM_H
#define EVS_SLAM_MESSAGE_NUM_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace evs_slam
{
template <class ContainerAllocator>
struct Num_ {
  typedef Num_<ContainerAllocator> Type;

  Num_()
  : name()
  , age(0)
  {
  }

  Num_(const ContainerAllocator& _alloc)
  : name(_alloc)
  , age(0)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  name;

  typedef int8_t _age_type;
  int8_t age;


  typedef boost::shared_ptr< ::evs_slam::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::evs_slam::Num_<ContainerAllocator>  const> ConstPtr;
}; // struct Num
typedef  ::evs_slam::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::evs_slam::Num> NumPtr;
typedef boost::shared_ptr< ::evs_slam::Num const> NumConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::evs_slam::Num_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::evs_slam::Num_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace evs_slam

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::evs_slam::Num_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::evs_slam::Num_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::evs_slam::Num_<ContainerAllocator> > {
  static const char* value() 
  {
    return "23b9bccd17c8042888a78e4f556ccd59";
  }

  static const char* value(const  ::evs_slam::Num_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x23b9bccd17c80428ULL;
  static const uint64_t static_value2 = 0x88a78e4f556ccd59ULL;
};

template<class ContainerAllocator>
struct DataType< ::evs_slam::Num_<ContainerAllocator> > {
  static const char* value() 
  {
    return "evs_slam/Num";
  }

  static const char* value(const  ::evs_slam::Num_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::evs_slam::Num_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string name\n\
int8 age\n\
\n\
";
  }

  static const char* value(const  ::evs_slam::Num_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::evs_slam::Num_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.name);
    stream.next(m.age);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct Num_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::evs_slam::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::evs_slam::Num_<ContainerAllocator> & v) 
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "age: ";
    Printer<int8_t>::stream(s, indent + "  ", v.age);
  }
};


} // namespace message_operations
} // namespace ros

#endif // EVS_SLAM_MESSAGE_NUM_H

